[package]
name = "rustly-store"
description = "Content-addressed object storage for Rustly."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
default = []
s3 = ["dep:object_store"]

[dependencies]
async-trait.workspace = true
rustly-cas.workspace = true
serde.workspace = true
serde_json.workspace = true
object_store = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
